security:
  basic:
    enabled: false
    username: user
    password: user

management:
  security:
    enabled: false
    username: user
    password: user
    
quoteServiceURL: http://quote-service-qa.cfapps.io/quote
